apiVersion: kustomize.config.k8s.io/v1beta1
namePrefix: non-prod-
commonLabels:
  env: non-prod
kind: Kustomization
resources:
  - ../../base
patches:
  - path: debug.yaml
images:
  - name: gitops
    newTag: "1.1"
