apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops
  name: gitops
spec:
  ports:
    - name: http
      port: 3030
      protocol: TCP
      targetPort: 3030
  selector:
    app: gitops
  type: NodePort
status:
  loadBalancer: {}
