apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
commonLabels:
  env: prod
resources:
  - ../../base
patches:
  - path: replica_count.yaml
images:
  - name: gitops
    newTag: "1.1"
